# _config.yml
baseurl: "" # this is important for GitHub Pages, leave it empty
url: "https://fajar035.github.io" # replace with your GitHub Pages URL

# Asset settings
sass:
  style: compressed

# Ensure Jekyll processes these directories
include:
  - assets
  - _sass

# Add the jekyll-assets plugin (optional)
plugins:
  - jekyll-assets

# Jekyll-assets configuration (optional)
assets:
  compress:
    css: true
    js: true
